name: daily
on:
  schedule:
    - cron: '* */24 * * *'
  workflow_dispatch:


jobs:
  setup:
    env:
      NO_INSTALL: 1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - run: curl -L setup.kmdk.uk | bash
  setup-win:
    env:
      NO_INSTALL: 1
    runs-on: windows-latest
    steps:
      - run: curl -L setup.kmdk.uk/setup.ps1 | pwsh
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - run: curl -L setup.kmdk.uk | bash
  install-win:
    runs-on: windows-latest
    steps:
      - run: curl -L setup.kmdk.uk/setup.ps1 | pwsh
