name: daily
on:
  schedule:
    - cron: '* */24 * * *'
  workflow_dispatch:

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - run: curl -sSLf setup.kmdk.uk | bash
  setup-win:
    runs-on: windows-latest
    steps:
      - run: curl -sSLf setup.kmdk.uk/setup.ps1 | pwsh
